[server]
device_ip       = 192.168.254.119
http_port       = 8080
rtsp_port       = 8554
device_uuid     = 12345678-1234-1234-1234-123456789abc

[auth]
username        = admin
password        = admin123

[backend]
ctrl_socket     = /tmp/mock-camera.sock
evt_socket      = /tmp/mock-camera-evt.sock
connect_timeout = 5

[discovery]
enable          = true
interface       = enp3s0
