#!/bin/bash
# scripts/patch_generated.sh
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
GEN_DIR="$ROOT_DIR/generated"
EXT_DIR="$ROOT_DIR/external/gsoap"

echo "[PATCH] Fixing generated files..."

# ── Fix 1: Inject wsse.h import into onvif.h BEFORE soapcpp2 ─────────────
# This makes soapcpp2 add wsse__Security to SOAP_ENV__Header struct.
ONVIF_H="$GEN_DIR/onvif.h"
if [ -f "$ONVIF_H" ]; then
    if ! grep -q '#import "wsse.h"' "$ONVIF_H"; then
        # Find wsse.h location
        WSSE_H=""
        for candidate in \
            "$EXT_DIR/import/wsse.h" \
            /usr/share/gsoap/import/wsse.h \
            /usr/local/share/gsoap/import/wsse.h; do
            if [ -f "$candidate" ]; then
                WSSE_H="$candidate"
                break
            fi
        done

        if [ -n "$WSSE_H" ]; then
            # Insert after the first #import line, or at top
            sed -i '1s|^|#import "wsse.h"\n|' "$ONVIF_H"
            echo "  [PATCHED] Added #import \"wsse.h\" to onvif.h (wsse found at $WSSE_H)"
        else
            echo "  [WARN] wsse.h not found — WS-Security header struct may be missing"
        fi
    else
        echo "  [OK] wsse.h already imported in onvif.h"
    fi
fi

# Fix 2: SOAP_ENV__Header is auto-generated by soapcpp2 from wsse.h import above.
# Do NOT manually declare it here — duplicate declaration causes soapcpp2 semantic error.

# ── Fix 3: Namespace map ──────────────────────────────────────────────────
NSMAP="$GEN_DIR/onvif.nsmap"
if [ ! -f "$NSMAP" ]; then
cat > "$NSMAP" << 'NSEOF'
struct Namespace namespaces[] = {
    {"SOAP-ENV","http://www.w3.org/2003/05/soap-envelope","http://schemas.xmlsoap.org/soap/envelope/",NULL},
    {"SOAP-ENC","http://www.w3.org/2003/05/soap-encoding","http://schemas.xmlsoap.org/soap/encoding/",NULL},
    {"xsi","http://www.w3.org/2001/XMLSchema-instance","http://www.w3.org/1999/XMLSchema-instance",NULL},
    {"xsd","http://www.w3.org/2001/XMLSchema",NULL,NULL},
    {"wsa5","http://www.w3.org/2005/08/addressing",NULL,NULL},
    {"wsse","http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd",NULL,NULL},
    {"wsu","http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd",NULL,NULL},
    {"wsdd","http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01",NULL,NULL},
    {"tt","http://www.onvif.org/ver10/schema",NULL,NULL},
    {"tds","http://www.onvif.org/ver10/device/wsdl",NULL,NULL},
    {"tr2","http://www.onvif.org/ver20/media/wsdl",NULL,NULL},
    {"tptz","http://www.onvif.org/ver20/ptz/wsdl",NULL,NULL},
    {"timg","http://www.onvif.org/ver20/imaging/wsdl",NULL,NULL},
    {"tev","http://www.onvif.org/ver10/events/wsdl",NULL,NULL},
    {"tan","http://www.onvif.org/ver20/analytics/wsdl",NULL,NULL},
    {"tdn","http://www.onvif.org/ver10/network/wsdl",NULL,NULL},
    {"wsnt","http://docs.oasis-open.org/wsn/b-2",NULL,NULL},
    {NULL,NULL,NULL,NULL}
};
NSEOF
    echo "  [CREATED] onvif.nsmap"
else
    echo "  [OK] onvif.nsmap exists"
fi

echo "[PATCH] Done."
